import React, { useEffect, useMemo, useState } from "react";
import Toast from "../components/Toast";

const CODE = "six";

// prize ladder for ranks 1–10
const PRIZES = [2000, 1000, 750, 400, 300, 200, 150, 100, 60, 40];

// matches your current behavior (static single avatar file)
const AVATAR_URL = () => "/1.jpg";

const fmt$ = (n) =>
  Number(n || 0).toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

const pad2 = (n) => String(n).padStart(2, "0");

const CROWN = (
  <svg className="crown" viewBox="0 0 24 24" fill="none" aria-hidden="true">
    <path
      d="M4 9l4 4 4-7 4 7 4-4v10H4V9z"
      stroke="rgba(227,185,61,.95)"
      strokeWidth="1.7"
      strokeLinejoin="round"
    />
    <path
      d="M6 19h12"
      stroke="rgba(227,185,61,.8)"
      strokeWidth="1.7"
      strokeLinecap="round"
    />
  </svg>
);

function applyPrizes(rows) {
  return rows.map((r, i) => ({
    ...r,
    prize: PRIZES[i] ?? 0,
    avatarSeed: r.username ?? `user-${i}`,
  }));
}

export default function Leaderboard() {
  const [toast, setToast] = useState({ show: false, text: "" });
  const [activeCasino, setActiveCasino] = useState("bitfortune");

  // dynamic leaderboard loaded from /public/leaderboard.json (generated by cron)
  const [leaderboard, setLeaderboard] = useState([]);
  const [loading, setLoading] = useState(true);

  // same logic as your HTML: END_AT = now + 36h (demo)
  const endAt = useMemo(() => Date.now() + 36 * 60 * 60 * 1000, []);
  const [t, setT] = useState({ dd: "00", hh: "00", mm: "00", ss: "00", tick: false });

  // countdown tick
  useEffect(() => {
    let prevSec = -1;
    const id = setInterval(() => {
      const remaining = Math.max(0, endAt - Date.now());
      const totalSec = Math.floor(remaining / 1000);
      if (totalSec === prevSec) return;
      prevSec = totalSec;

      const days = Math.floor(totalSec / 86400);
      const hours = Math.floor((totalSec % 86400) / 3600);
      const mins = Math.floor((totalSec % 3600) / 60);
      const secs = totalSec % 60;

      setT({
        dd: pad2(days),
        hh: pad2(hours),
        mm: pad2(mins),
        ss: pad2(secs),
        tick: true,
      });

      // remove tick quickly so animation can re-trigger
      setTimeout(() => setT((p) => ({ ...p, tick: false })), 50);
    }, 1000);

    return () => clearInterval(id);
  }, [endAt]);

  // load /leaderboard.json and keep it updated
  useEffect(() => {
    let alive = true;

    async function load() {
      try {
        setLoading(true);

        // cache-bust so you always get the latest file from your host/CDN
        const r = await fetch(`/leaderboard.json?v=${Date.now()}`, { cache: "no-store" });
        const data = await r.json();

        const normalized = (Array.isArray(data) ? data : [])
          .map((x, idx) => ({
            rank: x.rank ?? idx + 1,
            username: x.username ?? x.user_name ?? "hidden",
            wagered: Number(x.wagered ?? x.total_wager_usd ?? 0),
          }))
          .sort((a, b) => b.wagered - a.wagered)
          .map((x, idx) => ({ ...x, rank: idx + 1 }));

        if (!alive) return;
        setLeaderboard(applyPrizes(normalized));
      } catch (e) {
        console.error("Failed to load leaderboard.json", e);
        if (alive) setLeaderboard([]);
      } finally {
        if (alive) setLoading(false);
      }
    }

    load();

    // optional: refresh every 60s in browser
    const id = setInterval(load, 60000);

    return () => {
      alive = false;
      clearInterval(id);
    };
  }, []);

  const podiumConfig = [
    { dataIndex: 1, sizeClass: "h-2nd", label: 2 },
    { dataIndex: 0, sizeClass: "h-1st", label: 1 },
    { dataIndex: 2, sizeClass: "h-3rd", label: 3 },
  ];

  const maxWager = leaderboard[0]?.wagered ?? 1;

  async function copyCode() {
    try {
      await navigator.clipboard.writeText(CODE);
    } catch {
      // ignore
    }
    setToast({ show: true, text: `Copied: ${CODE}` });
  }

  if (loading) {
    return (
      <>
        <main className="wrap">
          <section className="hero">
            <h1>$5000 BitFortune Leaderboard</h1>
            <p className="sub">Loading live leaderboard…</p>
          </section>
        </main>
      </>
    );
  }

  return (
    <>
      <main className="wrap">
        <section className="hero">
          <h1>$5000 BitFortune Leaderboard</h1>
          <p className="sub">
            Compete in my Monthly Leaderboard and win huge prizes. Only eligible for users that signup via my link.
          </p>
          <p className="sub">Wagering on dice is prohibited!</p>

          <div className="pill-row" role="tablist" aria-label="Casino selection">
            <button
              className={`pill ${activeCasino === "bitfortune" ? "active" : ""}`}
              data-casino="bitfortune"
              role="tab"
              aria-selected={activeCasino === "bitfortune"}
              onClick={() => setActiveCasino("bitfortune")}
            >
              BitFortune
            </button>
          </div>

          <div className="code">

            <a href="https://join.bitfortune.com/six" target="_blank" rel="noopener noreferrer" className="btn-copy">
              Sign Up via my Link
            </a>

            
          </div>

          {leaderboard.length === 0 ? <p className="sub">No leaderboard data yet.</p> : null}
        </section>

        <section className="podium" aria-label="Top 3 players">
          {podiumConfig.map(({ dataIndex, sizeClass, label }) => {
            const u = leaderboard[dataIndex];
            if (!u) return null;

            const isWinner = dataIndex === 0;

            return (
              <article key={label} className={`card ${sizeClass}${isWinner ? " winner" : ""}`}>
                {isWinner ? <div className="halo" /> : null}
                <div className="card-inner">
                  {isWinner ? CROWN : <div style={{ height: 28 }} />}
                  <div className="badge">{label}</div>
                  <img className="avatar" src={AVATAR_URL(u.avatarSeed)} alt="" loading="lazy" />
                  <div className="name">{u.username}</div>
                  <div className="big">${fmt$(u.wagered)}</div>
                  <div className="meta">
                    <span>Wagered</span>
                    <span>Rank #{u.rank}</span>
                  </div>
                  <div className="prize">${fmt$(u.prize)}</div>
                </div>
              </article>
            );
          })}
        </section>

        <section className="countdown" aria-label="Time remaining">
          <div>Leaderboard ends in:</div>
          <div className="timer">
            <div className="timebox">
              <div className="num">{t.dd}</div>
              <div className="lbl">DAYS</div>
            </div>
            <div className="timebox">
              <div className="num">{t.hh}</div>
              <div className="lbl">HRS</div>
            </div>
            <div className="timebox">
              <div className="num">{t.mm}</div>
              <div className="lbl">MIN</div>
            </div>
            <div className="timebox">
              <div className={`num ${t.tick ? "tick" : ""}`}>{t.ss}</div>
              <div className="lbl">SEC</div>
            </div>
          </div>
        </section>

        <div className="headrow" aria-hidden="true">
          <div>#</div>
          <div>Username</div>
          <div style={{ textAlign: "right" }}>Wagered</div>
          <div className="prize-head" style={{ textAlign: "right" }}>
            Reward
          </div>
        </div>

        <section className="list" aria-label="Leaderboard positions 4–10">
          {leaderboard.slice(3).map((u) => {
            const pct = ((u.wagered / maxWager) * 100).toFixed(1);
            return (
              <div className="row" key={u.rank}>
                <div className="ribbon" aria-hidden="true" />
                <div className="rank">
                  <div className="chip">#{u.rank}</div>
                </div>
                <div className="user">
                  <img className="avatar-sm" src={AVATAR_URL(u.avatarSeed)} alt="" loading="lazy" />
                  <div style={{ minWidth: 0 }}>
                    <div className="uname">{u.username}</div>
                  </div>
                </div>

                <div className="val">
                  ${fmt$(u.wagered)}
                  <small>Wagered</small>
                  {/* bar exists in CSS — keep it available if you want to show it later */}
                  <div className="bar" aria-hidden="true" style={{ display: "none" }}>
                    <i style={{ width: `${pct}%` }} />
                  </div>
                </div>

                <div className="val reward prizecol">
                  ${fmt$(u.prize)}
                  <small>Reward</small>
                </div>
              </div>
            );
          })}
        </section>
      </main>

      <footer>
        <p>
          Gamble responsibly (18+). Only gamble what you can afford to lose. This site is for entertainment and
          promotional tracking.
        </p>
        <p>© {new Date().getFullYear()} sixchris</p>
      </footer>

      <Toast show={toast.show} text={toast.text} onHide={() => setToast((p) => ({ ...p, show: false }))} />
    </>
  );
}