name: Update Leaderboard

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run script
        run: node scripts/updateLeaderboard.js
        env:
          BITFORTUNE_API_KEY: ${{ secrets.BITFORTUNE_API_KEY }}

      - name: Commit new leaderboard
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/leaderboard.json
          git commit -m "Update leaderboard" || echo "No changes"
          git push